### ISSUE TITLE
[Request] Decoupling Hertz from bitUSD due to BSIP76's fake price feed

### ISSUE THREAD

**Issue by grctest** [clockworkgr/bitshares-pricefeed-js#5]
BSIP 76 (https://github.com/bitshares/bsips/issues/221) has now set fixed (fake) price feeds for bitUSD.

I'm unsure if this price feed script uses bitUSD as the price feed reference, but if it is then it's now producing inaccurate Hertz price feeds.

Can an alternative to bitUSD be provided for Hertz to become accurate again?

If this price feed script isn't using bitUSD for Hertz reference asset value then I'll close this issue, thanks 👍

**Comment by clockworkgr** [comment]
Script itself does not require updates.

However specific instances/configurations might.

As you can see in https://github.com/clockworkgr/bitshares-pricefeed-js/blob/master/sources/Hertz.js , the Hertz feed is implemented as a source that returns a HERTZ/USD exchange rate.

HERTZ/BTS feed would then be achieved by a configuration file that assigned sources to derive the feed from as the Hertz source and  at least one USD/BTS source.

If the USD/BTS source is configured as feed price from the DEX, the Hertz price would be out of whack. if a different(true) USD/BTS source was chosen. It would work fine.
